export const SELECT_TYPE = "SELECT_TYPE";
export const SELECT_LOCATION = "SELECT_LOCATION";
export const SELECT_STARS = "SELECT_STARS";
export const CREATE_NAME = "CREATE_NAME";
export const CREATE_DESCRIPTION = "CREATE_DESCRIPTION";
